export default [
  {
    ignores: [
      "src/**/*.md.jsx",
      "src/**/*.md.tsx",
      "src/**/*.md.js",
      "src/**/ANALISE_*",
      "src/**/ARQUITETURA_*",
      "src/**/APLICAVEL_*",
      "src/**/COMPARATIVO_*",
      "src/**/COMPARACAO_*",
      "src/**/CONFIRMACAO_*",
      "src/**/DECISAO_*",
      "src/**/DIAGNOSTICO_*",
      "src/**/ESTRATEGIA_*",
      "src/**/FLUXO_*",
      "src/**/MAPEAMENTO_*",
      "src/**/MELHORIAS_*",
      "src/**/PLANO_*",
      "src/**/PRINCIPIO_*",
      "src/**/PROJETO_*",
      "src/**/RECONCILIACAO_*",
      "src/**/VALIDACAO_*",
    ],
  },
];